-keep class com.bytedance.sdk.openadsdk.** { *; }
-keep public class com.bytedance.sdk.openadsdk.*{ public *; }
-keep public interface com.bytedance.sdk.openadsdk.downloadnew.** {*;}
-keep class com.pgl.sys.ces.* {*;}